name: Python Code Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pylint mypy
    - name: Run Black
      run: black --check .
    - name: Run Pylint
      run: pylint src
    - name: Run Mypy
      run: mypy src
    # TODO add pytest checks and install requirements.txt
